### ISSUE TITLE
mamba for OpenCE 1.10 fails at test stage

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce#939]
mamba for opence 1.10 fails with the following error:

The following error is seen while building mamba for OpenCE 1.10.

```
+ mamba --help
Traceback (most recent call last):
  File "/opt/conda/conda-bld/mamba-split_1699267509756/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/opt/conda/conda-bld/mamba-split_1699267509756/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.11/site-packages/mamba/mamba.py", line 16, in <module>
    from conda.cli.common import (
ImportError: cannot import name 'ensure_name_or_prefix' from 'conda.cli.common' (/opt/conda/conda-bld/mamba-split_1699267509756/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.11/site-packages/conda/cli/common.py)
Tests failed for mamba-1.4.9-opence_py311hfe9f712_1.conda - moving package to /opt/conda/conda-bld/broken
```

**Comment by cdeepali** [comment]
This is seen with newer version of conda and works with conda<23.9.0.

**Comment by Aman-Surkar** [comment]
Pinned conda to less than 23.7.4
